In [1]:
import os
import unicodedata
import pandas as pd
import numpy as np

In [2]:
REPO_URL = 'https://github.com/LuisBetancourt11/Proyecto_Ciencia_Datos'
REPO_DIR = 'Proyecto_Ciencia_Datos'

if not os.path.isdir(REPO_DIR):
    !git clone {REPO_URL}
else:
    print("El repositorio ya está clonado")
    !cd {REPO_DIR} && git pull

El repositorio ya está clonado; actualizando con git pull...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 306.63 KiB | 2.32 MiB/s, done.
From https://github.com/LuisBetancourt11/Proyecto_Ciencia_Datos
   a75e6b2..19e565e  main       -> origin/main
Updating a75e6b2..19e565e
Fast-forward
 data/raw/matriculas.csv | 13462 ++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 13462 insertions(+)
 create mode 100644 data/raw/matriculas.csv

In [3]:
raw_dir = REPO_DIR + '/data/raw/'
processed_dir = REPO_DIR + '/data/processed/'

# Asegurar que la carpeta de salida exista
os.makedirs(processed_dir, exist_ok=True)

print("raw_dir      :", raw_dir)
print("processed_dir:", processed_dir)
print("¿Existe el CSV?:", os.path.exists(raw_dir + 'matriculas.csv'))

raw_dir      : Proyecto_Ciencia_Datos/data/raw/
processed_dir: Proyecto_Ciencia_Datos/data/processed/
¿Existe el CSV?: True

In [4]:
df = pd.read_csv(raw_dir + 'matriculas.csv')
print(df.shape)
df.head()

(13461, 21)

,Género,Municipio de Nacimiento,País,Municipio Dirección,Barrio Dirección,Estrato,Estado civil,EPS,Grupo Sisben,Zona,...,Ocupación,Medio de Transporte,Multiculturalidad,Estado,Fecha de Matrícula,Jornada,Programa,Período,Nivel,Edad
0,Femenino,Medellín,Colombia,Envigado,Las Flores,3.0,Soltero(a),EPS Sura,Sin respuesta,Urbana,...,Estudiante básica,A Pie,No aplica,Graduado,2018-02-05T10:00:00Z,MEDIA TÉCNICA,MEDIA TÉCNICA TECNICO LABORAL AUXILIAR ADMINIS...,2018-2,SEMESTRE 2,20.0
1,Femenino,Envigado,Colombia,Envigado,San José,2.0,Soltero(a),EPS Sura,Sin respuesta,Urbana,...,Estudiante superior,Público Metro,No aplica,Graduado,2016-01-19T10:00:00Z,NOCHE,10T-TÉCNICO LABORAL EN AUXILIAR ADMINISTRATIVO...,2016-2,SEMESTRE 2,29.0
2,Masculino,Bogotá,Colombia,La Mesa,Sin respuesta,3.0,Soltero(a),No Aplica,Sin respuesta,Rural,...,Estudiante superior,Transmilenio,No aplica,Cancelado,2021-02-08T10:00:00Z,NOCHE,09T-TÉCNICO LABORAL EN AUXILIAR ADMINISTRATIVO,2021-2,SEMESTRE 1,19.0
3,Masculino,Envigado,Colombia,Envigado,San José,2.0,Soltero(a),SISBEN,B3,Urbana,...,Estudiante superior,Público Bus o Buseta,No aplica,Graduado,2020-01-17T10:00:00Z,DIURNA,01T-TÉCNICO LABORAL AUXILIAR DE TALENTO HUMANO,2021-1,SEMESTRE 2,21.0
4,Masculino,Medellín,Colombia,Envigado,El Salado,2.0,Soltero(a),Nueva Promotora de Salud - Nueva EPS,N0,Urbana,...,Estudiante superior,Moto,No aplica,Inactivo,2020-01-27T10:00:00Z,NOCHE,27T-TÉCNICO LABORAL EN MERCADEO Y VENTAS (Estu...,2020-1,SEMESTRE 1,20.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13461 entries, 0 to 13460
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Género                   13461 non-null  object
 1   Municipio de Nacimiento  13461 non-null  object
 2   País                     13461 non-null  object
 3   Municipio Dirección      13407 non-null  object
 4   Barrio Dirección         13461 non-null  object
 5   Estrato                  12193 non-null  float64
 6   Estado civil             13461 non-null  object
 7   EPS                      13460 non-null  object
 8   Grupo Sisben             13461 non-null  object
 9   Zona                     12160 non-null  object
 10  Nivel de formación       13461 non-null  object
 11  Ocupación                11543 non-null  object
 12  Medio de Transporte      13461 non-null  object
 13  Multiculturalidad        13461 non-null  object
 14  Estado                   13461 non-null  object
 15  Fecha de Matrícula       12244 non-null  object
 16  Jornada                  13338 non-null  object
 17  Programa                 13338 non-null  object
 18  Período                  13095 non-null  object
 19  Nivel                    13095 non-null  object
 20  Edad                     13460 non-null  float64
dtypes: float64(2), object(19)
memory usage: 2.2+ MB

## Estandarización de nombres de columnas

Las columnas vienen con tildes, mayúsculas y espacios (`Municipio de Nacimiento`,
`Fecha de Matrícula`, ...). Las normalizamos a `snake_case` sin tildes para trabajar
más cómodamente y evitar errores de tipeo. Se hace de forma programática (no a mano)
porque son 21 columnas.

In [6]:
def normalizar(texto):
    """minúsculas, sin tildes, espacios -> guion bajo"""
    texto = texto.strip().lower()
    # quitar tildes / acentos
    texto = unicodedata.normalize('NFKD', texto).encode('ascii', 'ignore').decode('ascii')
    texto = texto.replace(' ', '_')
    return texto

df.columns = [normalizar(c) for c in df.columns]
df.columns.tolist()

['genero',
 'municipio_de_nacimiento',
 'pais',
 'municipio_direccion',
 'barrio_direccion',
 'estrato',
 'estado_civil',
 'eps',
 'grupo_sisben',
 'zona',
 'nivel_de_formacion',
 'ocupacion',
 'medio_de_transporte',
 'multiculturalidad',
 'estado',
 'fecha_de_matricula',
 'jornada',
 'programa',
 'periodo',
 'nivel',
 'edad']

## Tratamiento de nulos "disfrazados"

En este dataset los faltantes no vienen como `NaN`, sino como texto:
`Sin respuesta`, `No Aplica`, `No aplica`, etc. Si no los convertimos a nulos reales,
`df.isnull()` no los detecta y contaminan el análisis.

Primero medimos cuántos nulos reales hay **antes** de la conversión.

In [8]:
df.isnull().sum()

genero                        0
municipio_de_nacimiento       0
pais                          0
municipio_direccion          54
barrio_direccion              0
estrato                    1268
estado_civil                  0
eps                           1
grupo_sisben                  0
zona                       1301
nivel_de_formacion            0
ocupacion                  1918
medio_de_transporte           0
multiculturalidad             0
estado                        0
fecha_de_matricula         1217
jornada                     123
programa                    123
periodo                     366
nivel                       366
edad                          1
dtype: int64

In [9]:
# Cadenas que en realidad representan ausencia de dato
sentinelas = ['sin respuesta', 'sin informacion', 'sin información',
              'no aplica', 'no aplica.', 'na', 'n/a', 'sin dato', 'ninguno']

# Reemplazar en todas las columnas de tipo texto
obj_cols = df.select_dtypes(include='object').columns
for col in obj_cols:
    mask = df[col].astype(str).str.strip().str.lower().isin(sentinelas)
    df.loc[mask, col] = np.nan

print("Nulos reales DESPUÉS de normalizar los textos faltantes:")
df.isnull().sum()

Nulos reales DESPUÉS de normalizar los textos faltantes:

genero                         0
municipio_de_nacimiento     1156
pais                          52
municipio_direccion           54
barrio_direccion            1372
estrato                     1268
estado_civil                1495
eps                         3089
grupo_sisben               10347
zona                        1327
nivel_de_formacion          3398
ocupacion                   1965
medio_de_transporte         3363
multiculturalidad          12628
estado                         0
fecha_de_matricula          1217
jornada                      123
programa                     123
periodo                      366
nivel                        366
edad                           1
dtype: int64

## Estandarización de tipos de datos

- `estrato` y `edad` vienen como `float` (3.0, 20.0). Los pasamos a entero anulable
  (`Int64`), que admite nulos.
- `fecha_de_matricula` viene como texto ISO (`2018-02-05T10:00:00Z`). La parseamos a
  datetime.

In [10]:
# Enteros anulables
for col in ['estrato', 'edad']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

# Fecha de matrícula -> datetime
df['fecha_de_matricula'] = pd.to_datetime(df['fecha_de_matricula'], errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13461 entries, 0 to 13460
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   genero                   13461 non-null  object
 1   municipio_de_nacimiento  12305 non-null  object
 2   pais                     13409 non-null  object
 3   municipio_direccion      13407 non-null  object
 4   barrio_direccion         12089 non-null  object
 5   estrato                  12193 non-null  Int64
 6   estado_civil             11966 non-null  object
 7   eps                      10372 non-null  object
 8   grupo_sisben             3114 non-null   object
 9   zona                     12134 non-null  object
 10  nivel_de_formacion       10063 non-null  object
 11  ocupacion                11496 non-null  object
 12  medio_de_transporte      10098 non-null  object
 13  multiculturalidad        833 non-null    object
 14  estado                   13461 non-null  object
 15  fecha_de_matricula       12244 non-null  datetime64[ns, UTC]
 16  jornada                  13338 non-null  object
 17  programa                 13338 non-null  object
 18  periodo                  13095 non-null  object
 19  nivel                    13095 non-null  object
 20  edad                     13460 non-null  Int64
dtypes: Int64(2), datetime64[ns, UTC](1), object(18)
memory usage: 2.2+ MB

## Columnas derivadas de la fecha

Extraemos componentes de la fecha que pueden ser útiles
para el EDA y el modelado.

In [11]:
df['anio_matricula'] = df['fecha_de_matricula'].dt.year
df['mes_matricula'] = df['fecha_de_matricula'].dt.month

df[['fecha_de_matricula', 'anio_matricula', 'mes_matricula']].head()

         fecha_de_matricula  anio_matricula  mes_matricula
0 2018-02-05 10:00:00+00:00          2018.0            2.0
1 2016-01-19 10:00:00+00:00          2016.0            1.0
2 2021-02-08 10:00:00+00:00          2021.0            2.0
3 2020-01-17 10:00:00+00:00          2020.0            1.0
4 2020-01-27 10:00:00+00:00          2020.0            1.0

In [13]:
df

,genero,municipio_de_nacimiento,pais,municipio_direccion,barrio_direccion,estrato,estado_civil,eps,grupo_sisben,zona,...,multiculturalidad,estado,fecha_de_matricula,jornada,programa,periodo,nivel,edad,anio_matricula,mes_matricula
0,Femenino,Medellín,Colombia,Envigado,Las Flores,3,Soltero(a),EPS Sura,NaN,Urbana,...,NaN,Graduado,2018-02-05 10:00:00+00:00,MEDIA TÉCNICA,MEDIA TÉCNICA TECNICO LABORAL AUXILIAR ADMINIS...,2018-2,SEMESTRE 2,20,2018.0,2.0
1,Femenino,Envigado,Colombia,Envigado,San José,2,Soltero(a),EPS Sura,NaN,Urbana,...,NaN,Graduado,2016-01-19 10:00:00+00:00,NOCHE,10T-TÉCNICO LABORAL EN AUXILIAR ADMINISTRATIVO...,2016-2,SEMESTRE 2,29,2016.0,1.0
2,Masculino,Bogotá,Colombia,La Mesa,NaN,3,Soltero(a),NaN,NaN,Rural,...,NaN,Cancelado,2021-02-08 10:00:00+00:00,NOCHE,09T-TÉCNICO LABORAL EN AUXILIAR ADMINISTRATIVO,2021-2,SEMESTRE 1,19,2021.0,2.0
3,Masculino,Envigado,Colombia,Envigado,San José,2,Soltero(a),SISBEN,B3,Urbana,...,NaN,Graduado,2020-01-17 10:00:00+00:00,DIURNA,01T-TÉCNICO LABORAL AUXILIAR DE TALENTO HUMANO,2021-1,SEMESTRE 2,21,2020.0,1.0
4,Masculino,Medellín,Colombia,Envigado,El Salado,2,Soltero(a),Nueva Promotora de Salud - Nueva EPS,N0,Urbana,...,NaN,Inactivo,2020-01-27 10:00:00+00:00,NOCHE,27T-TÉCNICO LABORAL EN MERCADEO Y VENTAS (Estu...,2020-1,SEMESTRE 1,20,2020.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13456,Masculino,Envigado,Colombia,Envigado,Barrio Mesa,3,Soltero(a),21) EPS Sura,D21,Urbana,...,NaN,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN
13457,Masculino,NaN,Colombia,Envigado,La Magnolia,3,NaN,COOSALUD EPS,B3,Urbana,...,Afrodescendiente,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN
13458,Masculino,NaN,Colombia,Envigado,San José,0,NaN,NaN,NaN,NaN,...,NaN,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN
13459,Femenino,Envigado,Colombia,Envigado,La Mina,3,Soltero(a),21) EPS Sura,N0,Urbana,...,NaN,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN
13460,Masculino,Envigado,Colombia,Envigado,San José,0,Soltero(a),NaN,B7,Urbana,...,NaN,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN

## Definición de la variable objetivo: `desercion`

El objetivo del proyecto es predecir la deserción. La columna `estado` contiene el
desenlace del estudiante. Primero revisamos qué valores existen realmente antes de mapear.

> **Decisión de negocio:** se considera deserción (`1`) a los
> estados que implican abandono (`Cancelado`, `Inactivo`, `Retirado`, ...), y no deserción
> (`0`) a los estados de permanencia o finalización exitosa (`Graduado`, `Activo`,
> `Egresado`, ...).

In [14]:
df['estado'].value_counts(dropna=False)

estado
Inactivo                    4838
Graduado                    3831
Activo                      2808
Cancelado                    759
Sancionado                   602
Aplazamiento Semestre        285
Sin estado                   243
Desertor                      79
Aplazamiento Actividades       8
Egresado                       7
Retiro - Aplazados             1
Name: count, dtype: int64

In [15]:
mapa_desercion = {
    # No deserción (permanece o terminó)
    'Graduado': 0,
    'Egresado': 0,
    'Activo': 0,
    'Aplazamiento Semestre': 0,
    'Aplazamiento Actividades': 0,
    # Deserción (abandonó)
    'Inactivo': 1,
    'Cancelado': 1,
    'Sancionado': 1,
    'Desertor': 1,
    'Retiro - Aplazados': 1,
    # Sin información -> se excluye del target
    'Sin estado': np.nan,
}

df['desercion'] = df['estado'].map(mapa_desercion)

# Verificar que no quedó ningún estado sin clasificar
sin_clasificar = df.loc[df['desercion'].isna() & df['estado'].notna(), 'estado'].unique()
print("Estados sin clasificar (deberían ser solo 'Sin estado'):", sin_clasificar)
print()
print(df['desercion'].value_counts(dropna=False))

Estados sin clasificar (deberían ser solo 'Sin estado'): ['Sin estado']

desercion
0.0    6939
1.0    6279
NaN     243
Name: count, dtype: int64

In [16]:
df

,genero,municipio_de_nacimiento,pais,municipio_direccion,barrio_direccion,estrato,estado_civil,eps,grupo_sisben,zona,...,estado,fecha_de_matricula,jornada,programa,periodo,nivel,edad,anio_matricula,mes_matricula,desercion
0,Femenino,Medellín,Colombia,Envigado,Las Flores,3,Soltero(a),EPS Sura,NaN,Urbana,...,Graduado,2018-02-05 10:00:00+00:00,MEDIA TÉCNICA,MEDIA TÉCNICA TECNICO LABORAL AUXILIAR ADMINIS...,2018-2,SEMESTRE 2,20,2018.0,2.0,0.0
1,Femenino,Envigado,Colombia,Envigado,San José,2,Soltero(a),EPS Sura,NaN,Urbana,...,Graduado,2016-01-19 10:00:00+00:00,NOCHE,10T-TÉCNICO LABORAL EN AUXILIAR ADMINISTRATIVO...,2016-2,SEMESTRE 2,29,2016.0,1.0,0.0
2,Masculino,Bogotá,Colombia,La Mesa,NaN,3,Soltero(a),NaN,NaN,Rural,...,Cancelado,2021-02-08 10:00:00+00:00,NOCHE,09T-TÉCNICO LABORAL EN AUXILIAR ADMINISTRATIVO,2021-2,SEMESTRE 1,19,2021.0,2.0,1.0
3,Masculino,Envigado,Colombia,Envigado,San José,2,Soltero(a),SISBEN,B3,Urbana,...,Graduado,2020-01-17 10:00:00+00:00,DIURNA,01T-TÉCNICO LABORAL AUXILIAR DE TALENTO HUMANO,2021-1,SEMESTRE 2,21,2020.0,1.0,0.0
4,Masculino,Medellín,Colombia,Envigado,El Salado,2,Soltero(a),Nueva Promotora de Salud - Nueva EPS,N0,Urbana,...,Inactivo,2020-01-27 10:00:00+00:00,NOCHE,27T-TÉCNICO LABORAL EN MERCADEO Y VENTAS (Estu...,2020-1,SEMESTRE 1,20,2020.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13456,Masculino,Envigado,Colombia,Envigado,Barrio Mesa,3,Soltero(a),21) EPS Sura,D21,Urbana,...,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN,0.0
13457,Masculino,NaN,Colombia,Envigado,La Magnolia,3,NaN,COOSALUD EPS,B3,Urbana,...,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN,0.0
13458,Masculino,NaN,Colombia,Envigado,San José,0,NaN,NaN,NaN,NaN,...,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN,0.0
13459,Femenino,Envigado,Colombia,Envigado,La Mina,3,Soltero(a),21) EPS Sura,N0,Urbana,...,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN,0.0
13460,Masculino,Envigado,Colombia,Envigado,San José,0,Soltero(a),NaN,B7,Urbana,...,Activo,NaT,MEDIA TÉCNICA,MEDIA TÉCNICA TÉCNICO EN MARKETING Y VENTA DE ...,2026-MT,ONCE,16,NaN,NaN,0.0

## Revisión de duplicados

El dataset son *matrículas*, no estudiantes únicos. Se revisará filas
completamente duplicadas.

In [22]:
print("Filas duplicadas (exactas):", df.duplicated().sum())
df = df.drop_duplicates().reset_index(drop=True)

Filas duplicadas (exactas): 0

Anteriormente se detectaron 64 filas duplicadas, pero al ejecutar el código "df = df.drop_duplicates().reset_index(drop=True)" se eliminan las filas duplicadas.

In [21]:
filas_duplicadas = df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist())
print(f"Total de filas duplicadas: {len(filas_duplicadas)}")
print()
filas_duplicadas

Total de filas duplicadas: 0

Empty DataFrame
Columns: [genero, municipio_de_nacimiento, pais, municipio_direccion, barrio_direccion, estrato, estado_civil, eps, grupo_sisben, zona, nivel_de_formacion, ocupacion, medio_de_transporte, multiculturalidad, estado, fecha_de_matricula, jornada, programa, periodo, nivel, edad, anio_matricula, mes_matricula, desercion]
Index: []

[0 rows x 24 columns]

## Guardar los datos limpios

Guardar el dataset limpio, estandarizado y con la variable objetivo.

In [24]:
from getpass import getpass

# 1. GUARDA el dataset limpio
ruta_salida = processed_dir + 'matriculas_limpias.csv'
df.to_csv(ruta_salida, index=False)
print("Guardado en:", ruta_salida)
print("¿Existe el archivo?:", os.path.exists(ruta_salida))
print("Dimensiones finales:", df.shape)

!git config --global user.email "betancourt1659@gmail.com"
!git config --global user.name "LuisBetancourt11"

# 3. Token de acceso personal
usuario = "LuisBetancourt11"
repo = "Proyecto_Ciencia_Datos"
token = getpass("Access Token: ")

# Enviar al repo de github
!cd {repo} && git add data/processed/matriculas_limpias.csv && \
  git commit -m "Se agregó dataset limpio generado en 02_Limpieza" && \
  git remote set-url origin https://{usuario}:{token}@github.com/{usuario}/{repo}.git && \
  git push origin

Guardado en: Proyecto_Ciencia_Datos/data/processed/matriculas_limpias.csv
¿Existe el archivo?: True
Dimensiones finales: (13397, 24)
Pega tu GitHub Personal Access Token: ··········
[main 2eed819] Agregar dataset limpio generado en 02_Limpieza
 1 file changed, 13398 insertions(+)
 create mode 100644 data/processed/matriculas_limpias.csv
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 324.09 KiB | 3.68 MiB/s, done.
Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/LuisBetancourt11/Proyecto_Ciencia_Datos.git
   19e565e..2eed819  main -> main